[package]
version = "0.1.0"
name = "block-processing-script"
edition = "2021"
default-run = "block_processing"

[[bin]]
name = "block_processing"
path = "src/bin/main.rs"

[[bin]]
name = "evm"
path = "src/bin/evm.rs"

[[bin]]
name = "vkey"
path = "src/bin/vkey.rs"

[dependencies]
sp1-sdk = "5.0.0"
serde_json = { workspace = true }
serde = { workspace = true }
hex = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
dotenv = "0.15.0"
clap = { version = "4.0", features = ["derive", "env"] }
state_processing_sp1 = { path = "../../state_processing_sp1" }
types = { workspace = true }
ethereum_ssz = { workspace = true }
bls = { workspace = true }

[build-dependencies]
sp1-build = "5.0.0"
